export const LOGIN="LOGIN"
export const LOGOUT = "LOGOUT"
export const FETCH_PRODUCTS="FETCH_PRODUCTS"
export const ADD_PRODUCT="ADD_PRODUCT"
export const EDIT_PRODUCT="EDIT_PRODUCT"
export const GET_PRODUCT_BY_ID="GET_PRODUCT_BY_ID"
export const FETCH_BILLS="FETCH_BILLS"
export const CREATE_BILLS="CREATE_BILLS"
export const GET_BILL_BY_ID="GET_BILL_BY_ID"
export const GET_SALES_REPORTS="GET_SALES_REPORTS"
export const GET_REVENUE_REPORTS="GET_REVENUE_REPORTS"
export const GET_VISITOR_REPORTS="GET_VISITOR_REPORTS"
export const GET_PRODUCT_REPORTS="GET_PRODUCT_REPORTS"
export const GET_TOTAL_REPORTS="GET_TOTAL_REPORTS"
export const REPORTS_COMPLETE ="REPORTS_COMPLETE";

export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_PUSH_SUCCESS = "ORDER_PUSH_SUCCESS"
//----------------------///


export const CATALOG_LIST_REQUEST ="CATALOG_LIST_REQUEST";
export const CATALOG_LIST_SUCCESS ="CATALOG_LIST_SUCCESS";
export const CATALOG_LIST_FAIL ="CATALOG_LIST_FAIL";

export const PRODUCT_LIST_REQUEST ="PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS ="PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL ="PRODUCT_LIST_FAIL";

export const PRODUCT_REQUEST ="PRODUCT_REQUEST";
export const PRODUCT_SUCCESS ="PRODUCT_SUCCESS";
export const PRODUCT_FAIL ="PRODUCT_FAIL";

export const CART_LIST_ITEM ="CART_LIST_ITEM";
export const LIST_ORDER_ACCESS ="LIST_ORDER_ACCESS";
export const PUSH_PAYMENT_ACCESS ="PUSH_PAYMENT_ACCESS";
