export const REPORTS_SALES ="REPORTS_SALES";
export const REPORTS_REVENUE ="REPORTS_REVENUE";
export const REPORTS_VISITOR ="REPORTS_VISITOR";
export const REPORTS_PRODUCT ="REPORTS_PRODUCT";
export const REPORTS_TOTAL ="REPORTS_TOTAL";
